name: keyflow
base: core22
icon: snap/gui/icon.png
version: '1.0.1'
summary: A secure password manager built with Python and PySide6.
description: |
  Keyflow is a modern, secure password manager that helps you store and organize your passwords locally.

grade: devel
confinement: devmode

apps:
  keyflow:
    command: bin/keyflow
    extensions: [gnome]
    common-id: keyflow.desktop
    plugs:
      - home
      - network
      - removable-media

parts:
  keyflow:
    plugin: python
    source: .
    build-environment:
      - SNAP_RESULT_USER: "snap_daemon"
      
    override-build: |
      craftctl default
      # Copiar assets al directorio donde main.py espera encontrarlos (site-packages)
      cp -r $CRAFT_PART_SRC/assets $CRAFT_PART_INSTALL/lib/python3.10/site-packages/

    stage-packages:
      - libxkbcommon-x11-0
      - libxcb-cursor0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-render0
      - libxcb-shape0
      - libxcb-sync1
      - libxcb-xfixes0
      - libxcb-xinerama0
      - libxcb-xkb1
      - libx11-xcb1
      - libgl1

